"""empty message

Revision ID: 6919ab2208c8
Revises: 9c0262bf7f9b
Create Date: 2023-04-18 23:49:19.807777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6919ab2208c8'
down_revision = '9c0262bf7f9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razon_social', sa.String(length=120), nullable=False),
    sa.Column('rut', sa.String(length=80), nullable=False),
    sa.Column('nombre_fantasia', sa.String(length=120), nullable=False),
    sa.Column('estado', sa.String(length=120), nullable=False),
    sa.Column('direccion_facturacion', sa.String(length=120), nullable=False),
    sa.Column('region', sa.String(length=120), nullable=False),
    sa.Column('comuna', sa.String(length=120), nullable=False),
    sa.Column('nombre_contacto_facturacion', sa.String(length=120), nullable=False),
    sa.Column('telefono_contacto_facturacion', sa.Integer(), nullable=False),
    sa.Column('email_contacto_facturacion', sa.String(length=120), nullable=False),
    sa.Column('cargo_contacto_facturacion', sa.String(length=120), nullable=True),
    sa.Column('nombre_contacto_cobranza', sa.String(length=120), nullable=False),
    sa.Column('telefono_contacto_cobranza', sa.Integer(), nullable=False),
    sa.Column('email_contacto_cobranza', sa.String(length=120), nullable=False),
    sa.Column('cargo_contacto_cobranza', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_contacto_cobranza'),
    sa.UniqueConstraint('email_contacto_facturacion'),
    sa.UniqueConstraint('razon_social'),
    sa.UniqueConstraint('rut'),
    sa.UniqueConstraint('telefono_contacto_cobranza'),
    sa.UniqueConstraint('telefono_contacto_facturacion')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('empresa')
    # ### end Alembic commands ###
