"""empty message

Revision ID: 8acbcf052eed
Revises: 491b0db7798c
Create Date: 2023-04-18 23:21:40.659083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8acbcf052eed'
down_revision = '491b0db7798c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_master', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('clave', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('nombre_usuario_master', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('telefono', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('cargo', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('observaciones', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('peril_usuario', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('peril_admin', sa.Boolean(), nullable=False))
        batch_op.create_unique_constraint(None, ['telefono'])
        batch_op.create_unique_constraint(None, ['usuario_master'])
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('peril_admin')
        batch_op.drop_column('peril_usuario')
        batch_op.drop_column('observaciones')
        batch_op.drop_column('cargo')
        batch_op.drop_column('telefono')
        batch_op.drop_column('nombre_usuario_master')
        batch_op.drop_column('clave')
        batch_op.drop_column('usuario_master')

    # ### end Alembic commands ###
