"""empty message

Revision ID: 9d8a4e427012
Revises: ee98a8f44674
Create Date: 2023-04-19 02:06:39.994199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d8a4e427012'
down_revision = 'ee98a8f44674'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.alter_column('razon_social',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('rut',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('nombre_fantasia',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('direccion_facturacion',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('region',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('comuna',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('telefono_contacto_facturacion',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('telefono_contacto_cobranza',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=80),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('telefono',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('telefono',
               existing_type=sa.String(length=80),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.alter_column('telefono_contacto_cobranza',
               existing_type=sa.String(length=80),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('telefono_contacto_facturacion',
               existing_type=sa.String(length=80),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('comuna',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('region',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('direccion_facturacion',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('nombre_fantasia',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('rut',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('razon_social',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###
