"""empty message

Revision ID: ad4bb2cc7176
Revises: e454dffc591e
Create Date: 2023-04-24 21:09:18.853626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad4bb2cc7176'
down_revision = 'e454dffc591e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_usuario_master_creador', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fecha_y_hora_creacion', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('id_usuario_master_modificador', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fecha_y_hora_modificacion', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_column('fecha_y_hora_modificacion')
        batch_op.drop_column('id_usuario_master_modificador')
        batch_op.drop_column('fecha_y_hora_creacion')
        batch_op.drop_column('id_usuario_master_creador')

    # ### end Alembic commands ###
