"""empty message

Revision ID: f319ba800be6
Revises: 6919ab2208c8
Create Date: 2023-04-19 00:26:45.247481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f319ba800be6'
down_revision = '6919ab2208c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('fecha_y_hora_creacion',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('fecha_y_hora_modificacion',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('fecha_y_hora_modificacion',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('fecha_y_hora_creacion',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###
